import * as WebBrowser from 'expo-web-browser';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Icon } from '@/components/Icon';
import { MeroaMark } from '@/components/MeroaMark';
import { PrimaryButton } from '@/components/PrimaryButton';
import { theme } from '@/constants/theme';
import { useUpdatePrefs } from '@/features/profile/queries';
import { privacyUrl } from '@/lib/legal-urls';

// Apple 5.1.2(i): the explicit-consent gate the user passes once (and can revoke
// in You → AI data sharing). Granting it flips the nav guard in _layout.tsx, which
// moves the user on to the tabs — this screen never navigates itself. The server
// separately refuses every send until consent is recorded (lib/consent.ts), so
// this screen is the humane surface, not the enforcement.
export default function AiConsentScreen() {
  const updatePrefs = useUpdatePrefs();

  const agree = () => {
    if (updatePrefs.isPending) return;
    // Client asserts only `granted`; the server stamps `at` + `version`.
    updatePrefs.mutate({ aiConsent: { granted: true } });
  };

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.header}>
          <MeroaMark size={56} glow />
          <Text style={styles.title}>Before we start chatting</Text>
          <Text style={styles.subtitle}>
            {"Meroa's replies are generated by a third-party AI service. So you know exactly what that means:"}
          </Text>
        </View>

        <View style={styles.points}>
          <Point
            text="The messages you send Meroa are sent to that AI service to generate a reply."
          />
          <Point text="They travel over an encrypted connection (HTTPS)." />
          <Point text="Your phone number and account identity are never sent to it." />
          <Point text="Chat can't work without this — you can withdraw it anytime in Settings." />
        </View>

        <Pressable onPress={() => WebBrowser.openBrowserAsync(privacyUrl())} hitSlop={8}>
          <Text style={styles.link}>Read our Privacy Policy</Text>
        </Pressable>

        {updatePrefs.isError ? (
          <Text style={styles.error}>{"Couldn't save that. Check your connection and try again."}</Text>
        ) : null}
      </ScrollView>

      <View style={styles.footer}>
        <PrimaryButton
          label={updatePrefs.isPending ? 'Saving…' : 'I agree'}
          onPress={updatePrefs.isPending ? undefined : agree}
          style={updatePrefs.isPending ? styles.ctaDisabled : undefined}
        />
        {updatePrefs.isPending ? <ActivityIndicator style={styles.spinner} color={theme.dim} /> : null}
      </View>
    </SafeAreaView>
  );
}

function Point({ text }: { text: string }) {
  return (
    <View style={styles.point}>
      <View style={styles.pointIcon}>
        <Icon name="check" size={14} color={theme.blue} />
      </View>
      <Text style={styles.pointText}>{text}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.bg },
  content: { padding: 24, paddingTop: 40, gap: 28 },
  header: { alignItems: 'center', gap: 12 },
  title: { color: theme.text, fontSize: 26, fontWeight: '700', letterSpacing: -0.5, textAlign: 'center', marginTop: 8 },
  subtitle: { color: theme.dim, fontSize: 15, lineHeight: 22, textAlign: 'center' },
  points: { gap: 16 },
  point: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
  pointIcon: {
    width: 26,
    height: 26,
    borderRadius: 999,
    backgroundColor: 'rgba(10,132,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  pointText: { flex: 1, color: theme.text, fontSize: 15, lineHeight: 22 },
  link: { color: theme.blue, fontSize: 15, fontWeight: '600', textAlign: 'center' },
  error: { color: theme.danger, fontSize: 14, textAlign: 'center' },
  footer: { padding: 24, paddingTop: 8 },
  ctaDisabled: { opacity: 0.6 },
  spinner: { position: 'absolute', right: 44, top: 24 },
});
